//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace framework_sattarova
{
    using System;
    using System.Collections.Generic;
    
    public partial class corzina
    {
        public int ID { get; set; }
        public int userID { get; set; }
        public int productID { get; set; }
    
        public virtual person person { get; set; }
        public virtual products products { get; set; }
    }
}
